language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
install:
    - python setup.py -q install
    - pip install unittest2
script: 
    - nosetests
    - python -m doctest README.rst
