language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - REQUIREMENTS=""
  - REQUIREMENTS="unittest2"
install:
    - pip install $REQUIREMENTS
    - python setup.py -q install
script:
    - py.test --tb=native jsonschema
    - python -m doctest README.rst
